export const ar = {
  welcome: "مرحبا بك",
  to: "في",
  signIn: "تسجيل الدخول",
  manageMate: "ManageMate",
  items: "الأصناف",
  users: "المستخدمون",
  payments: "المدفوعات",
  profits: "الارباح",
  itemsDescription: "إدارة المنتجات والمخزون",
  usersDescription: "عرض وإدارة المستخدمين",
  paymentsDescription: "مراجعة المدفوعات",
  profitsDescription: "تتبع أدائك المالي",
  logInToYourAccount: "تسجيل الدخول إلى حسابك",
  newToManageMate: "جديد في ManageMate؟",
  alreadyHaveAnAccount: "هل لديك حساب بالفعل؟",
  signUpForAnAccount: "إنشاء حساب",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  logIn: "تسجيل الدخول",
  logOut: "تسجيل الخروج",
  createAccount: "إنشاء حساب",
  signUp: "إنشاء",
  enterEmail: "أدخل البريد الإلكتروني",
  enterPassword: "أدخل كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  confirmYourPassword: "أكد كلمة المرور الخاصة بك",
  InvalidEmailAddress: "عنوان البريد الإلكتروني غير صالح",
  PasswordMustBe: "يجب أن تكون كلمة المرور 6 أحرف على الأقل!",
  PasswordsDoNotMatch: "كلمات المرور غير متطابقة!",
  PageNotFound: "الصفحة غير موجودة.",
  CantFindPage: "عذرًا، لا يمكننا العثور على الصفحة التي تبحث عنها.",
  SearchPlaceholder: "بحث...",
  name: "الاسم",
  price: "السعر",
  pricePerItem: 'سعر الوحدة',
  enterPricePerItem: 'أدخل سعر الوحدة',
  date: 'التاريخ',
  enterDate: 'أدخل التاريخ',
  add: 'إضافة',
  quantity: "الكمية",
  barCode: "الباركود",
  total: 'المجموع',
  netProfit: 'الربح الصافي',
  description: "الوصف",
  enterItemName: "أدخل اسم الصنف",
  enterItemPrice: "أدخل سعر الصنف",
  enterItemQuantity: "أدخل كمية الصنف",
  enterItemBarCode: "أدخل باركود الصنف",
  scanBarCode: "مسح الباركود",
  enterItemDescription: "أدخل وصف الصنف",
  addItem: "إضافة صنف",
  updateItem: "تعديل الصنف",
  phoneNumber: "رقم الهاتف",
  role: "الدور",
  enterName: "أدخل الاسم",
  enterPhoneNumber: "أدخل رقم الهاتف",
  enterRole: "أدخل الدور",
  addUser: "إضافة مستخدم",
  noItemFound: "لم يتم العثور على العنصر",
  edit: "تعديل",
  delete: "حذف",
  language: "اللغة",
  dark: "داكن",
  light: "فاتح",
  english: 'English',
  language: 'العربية',
  allFieldsRequired: 'جميع الحقول مطلوبة',
  addedSuccessfully: 'تمت الإضافة بنجاح',
  updatedSuccessfully: 'تم التحديث بنجاح',
  deletedSuccessfully: 'تم الحذف بنجاح',
  addedUnsuccessfully: 'فشل الإضافة',
  updatedUnsuccessfully: 'فشل التحديث',
  deletedUnsuccessfully: 'فشل الحذف',
};

export default ar;
