const en = {
  welcome: 'Welcome',
  to: 'to',
  signIn: 'Sign in',
  manageMate: 'ManageMate',
  items: 'Items',
  users: 'Users',
  payments: 'Payments',
  profits: 'Profits',
  itemsDescription: 'Manage products and inventory',
  usersDescription: 'View and manage users',
  paymentsDescription: 'Review payments',
  profitsDescription: 'Track your financial performance',
  logInToYourAccount: 'Login to your account',
  newToManageMate: 'New to ManageMate?',
  alreadyHaveAnAccount: 'Already have an account?',
  signUpForAnAccount: 'Sign up for an account',
  email: 'Email',
  password: 'Password',
  logIn: 'Login',
  logOut: 'Logout',
  createAccount: 'Create an account',
  signUp: 'Sign up',
  enterEmail: 'Enter Email',
  enterPassword: 'Enter Password',
  confirmPassword: 'Confirm Password',
  confirmYourPassword: 'Confirm your password',
  InvalidEmailAddress: 'Invalid email address',
  PasswordMustBe: 'Password must be at least 6 characters long!',
  PasswordsDoNotMatch: 'Passwords do not match!',
  PageNotFound: 'Page not found.',
  CantFindPage: 'Sorry, we can’t find the page you’re looking for.',
  SearchPlaceholder: 'Search...',
  name: 'Name',
  price: 'Price',
  pricePerItem: 'Price Per Item',
  enterPricePerItem: 'Enter Price Per Item',
  date: 'Date',
  enterDate: 'Enter Date',
  add: 'Add',
  quantity: 'Quantity',
  barCode: 'Barcode',
  total: 'Total',
  netProfit: 'Net Profit',
  description: 'Description',
  enterItemName: 'Enter Item Name',
  enterItemPrice: 'Enter Item Price',
  enterItemQuantity: 'Enter Item Quantity',
  enterItemBarCode: 'Enter Item Barcode',
  scanBarCode: 'Scan Barcode',
  enterItemDescription: 'Enter Item Description',
  addItem: 'Add Item',
  updateItem: 'Update Item',
  phoneNumber: 'Phone Number',
  role: 'Role',
  enterName: 'Enter Name',
  enterPhoneNumber: 'Enter Phone Number',
  enterRole: 'Enter Role',
  addUser: 'Add User',
  noItemFound: 'No Item Found.',
  edit: 'Edit',
  delete: 'Delete',
  language: 'Language',
  dark: 'Dark',
  light: 'Light',
  language: 'English',
  allFieldsRequired: 'All fields are required',
  addedSuccessfully: 'Added successfully',
  updatedSuccessfully: 'Updated successfully',
  deletedSuccessfully: 'Deleted successfully',
  addedUnsuccessfully: 'Failed to add',
  updatedUnsuccessfully: 'Failed to update',
  deletedUnsuccessfully: 'Failed to delete',
};

export default en;
